name: Deploy Admin UI
on:
  push:
    branches: [ "main", "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 88.222.214.155
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/var/www/ssbwithisv/admin"
